jwt:
  # ?????? ?? secret key?? HS256 ????? ???? ??, 256???? ????. (??? ??? 8?? -> 32?? ??)
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/holymorning
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace